# Generated by Django 5.0.4 on 2024-05-04 21:26

import django.contrib.auth.validators
import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExinakaiUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует.'}, help_text='Не более 16 символов, не менее 5. Буквы, цифры, @/./+/-/_.', max_length=16, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), django.core.validators.MinLengthValidator(5)], verbose_name='Имя пользователя')),
                ('email', models.EmailField(help_text='Электронная почта для сброса пароля.', max_length=254, unique=True, verbose_name='Почта')),
                ('avatar', models.ImageField(default='default-user-icon.jpg', upload_to=users.models.get_uploaded_avatar_path, verbose_name='Аватарка')),
                ('timezone', models.CharField(default='Europe/London', max_length=64, verbose_name='Временная зона')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Время регистрации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен ли')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'exinakai_user',
            },
        ),
    ]
